# Book settings
title: Akadémia Y
author: Dominik Csiba
logo: images/Y.jpg

html:
  favicon: images/Y.jpg
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://cedeerwe.github.io/y

latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  notebook_interface        : "jupyterlab"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"
  thebelab                  : true

repository:
  url                         : https://github.com/cedeerwe/y
  path_to_book                : "book"
  branch: master

sphinx:
  config:
    mathjax_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "qq": ["\\quad#1\\quad", 1]